"use client"
import Header from '@/components/Header'
import './globals.css'
import { Inter } from 'next/font/google'
import Footer from '@/components/Footer'
import Sidebar from '@/components/Sidebar'
import { usePathname } from 'next/navigation'
import { ThemeProvider } from 'next-themes'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  let show = true
  const path = usePathname()
  if (path == '/login' || path == '/register') {
    show = false
  }
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider>
          {show && <Header />}
          <div className='flex'>
            {show && <Sidebar />}
            <main className='w-full'>
              {children}
            </main>
          </div>
          {show && <Footer />}
        </ThemeProvider>
      </body>
    </html>
  )
}
